version: "3.9"
services:
  freecad:
    container_name: FreeCAD
    image: ghcr.io/linuxserver/freecad:latest
    # Healthcheck replaced with a simpler (but less robust) method.  Might still fail.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    security_opt:
      - no-new-privileges:true
      # seccomp:unconfined is generally discouraged for security reasons.  Consider removing.
    restart: on-failure:5
    ports:
      - "3935:3000"
    # Volume mapping adjusted for Windows.  Replace with your actual Windows path.
    volumes:
      - "C:/Users/<YOUR_USERNAME>/docker/freecad:/config:rw"
    environment:
      CUSTOM_USER: marius
      PASSWORD: mariushosting
      TZ: Europe/Bucharest
      # PUID and PGID are removed as they are Linux-specific.
